-- Your SQL goes here
CREATE TABLE games
(
	game_id char(12) PRIMARY KEY,
	visteam char(3) not null,
	hometeam char(3) not null,
	game_date date not null,
	number integer default 0 not null,
	starttime time not null,
	daynight varchar(16) not null,
	usedh boolean default false not null,
	pitches varchar(7) not null,
	umphome char(8),
	ump1b char(8),
	ump2b char(8),
	ump3b char(8),
	umplf char(8),
	umprf char(8),
	fieldcond varchar(7) not null,
	precip varchar(7) not null,
	sky varchar(7) not null,
	temp integer default 0 not null,
	winddir varchar(7) not null,
	windspeed integer default 0 not null,
	timeofgame integer default 0 not null,
	attendance integer default 0 not null,
	site char(5) not null,
	wp char(8) not null,
	lp char(8) not null,
	save char(8),
	gwrbi char(8),
	edittime timestamp,
	howscored varchar(32),
	inputprogvers varchar(32),
	inputter varchar(32),
	inputtime timestamp,
	scorer varchar(32),
	translator varchar(32)
)
